version: '2'

services:
  caddy:
    restart: unless-stopped
    image: abiosoft/caddy:latest
    depends_on:
      - nginxproxymanager
    environment:
      ACME_AGREE: "true"
      DDNS_FRONTEND_HOST: npm:81
      DDNS_CADDY_DOMAIN: revprox.slyfi             
      DDNS_CADDY_TLS_EMAIL: wirewrex@protonmail.com
    volumes:
      - "./ddns-handshake-dane/caddy/Caddyfile:/etc/Caddyfile"
      - "./ddns-handshake-dane/.caddy_mount:/root/.caddy"
    ports:
      - "80:80"
      - "443:443"
