version: '2'

services:
  caddy:
    restart: unless-stopped
    image: abiosoft/caddy:no-stats
    environment:
      ACME_AGREE: "true"
      FRONTEND_HOST: npm:81
      CADDY_DOMAIN: revprox.slyfi             
      CADDY_TLS_EMAIL: wirewrex@protonmail.com
    volumes:
      - "./caddy-reverse-proxy-handshake/caddy/Caddyfile:/etc/Caddyfile"
      - "./caddy-reverse-proxy-handshake/.caddy_mount:/root/.caddy"
    ports:
      - "80:80"
      - "443:443"
